---
title: "découverte"
author: oim
email: oimemail
description: 
 lalali lalala

# social links
twitter_username: your-twitter-handle 
github_username:  your-github-handle 

show_excerpts: true 
theme: minima
---
